name: cuistoloco
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  twilio_flutter: ^0.0.9
  flutter_dotenv: ^5.2.1
  camera: ^0.10.5+4
  google_mlkit_image_labeling: ^0.13.0
  http: ^0.13.6
  googleapis: ^13.1.0
  google_ml_kit: ^0.19.0
  googleapis_auth: ^1.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
  - test_credential.json